package me.heyboy.mymvpdemo.model.data;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import me.heyboy.mymvpdemo.model.entities.ImgRecorder;

import me.heyboy.mymvpdemo.model.dao.ImgRecorderDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig imgRecorderDaoConfig;

    private final ImgRecorderDao imgRecorderDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        imgRecorderDaoConfig = daoConfigMap.get(ImgRecorderDao.class).clone();
        imgRecorderDaoConfig.initIdentityScope(type);

        imgRecorderDao = new ImgRecorderDao(imgRecorderDaoConfig, this);

        registerDao(ImgRecorder.class, imgRecorderDao);
    }
    
    public void clear() {
        imgRecorderDaoConfig.clearIdentityScope();
    }

    public ImgRecorderDao getImgRecorderDao() {
        return imgRecorderDao;
    }

}
